main:
  - weight: 1
    identifier: about
    name: About Me ğŸ§‘â€ğŸ’»
    url: /about-me/
  - weight: 4
    identifier: photos
    name: Photos ğŸ“¸
    url: https://www.flickr.com/photos/burakibis/
  - weight: 3
    identifier: digital-garden
    name: Digital Garden ğŸª´
    url: https://garden.buraste.com
  - weight: 2
    identifier: roadmap
    name: Roadmap ğŸ“
    url: /roadmap/
