title: buraste blog
description: KiÅŸisel Blog
author: me
homeInfoParams:
  Title: Merhaba ğŸ‘‹ yaÅŸadÄ±klarÄ±ma dair bazÄ± ÅŸeyler yazÄ±yorum.
  Content: '
    GÃ¼n boyu online bir [spiritÃ¼el dÃ¼kkanÄ±](https://hellominaste.com) yÃ¶netiyorum.
    Geceleri kod yazarak dÃ¼nyayÄ± kurtarÄ±yorum. Bir sonraki sÃ¼per novaya kadar
    yataklarÄ±nÄ±zda rahatÃ§a uyuyabilirsiniz ğŸª Benimle ilgili daha fazlasÄ± iÃ§in ğŸ‘‰
    [tÄ±kla](/tr/hakkimda)
    '
