title: buraste blog
description: KiÅŸisel Blog
homeInfoParams:
  Title: Merhaba ğŸ‘‹ yaÅŸadÄ±klarÄ±ma dair bazÄ± ÅŸeyler yazÄ±yorum.
  Content:
    'GÃ¼n boyu online bir [spiritÃ¼el dÃ¼kkanÄ±](https://hellominaste.com) yÃ¶netiyorum.
    Geceleri micro service iÃ§in yeminler edip sabah vazgeÃ§iyorum ğŸª Benimle ilgili daha fazlasÄ± iÃ§in ğŸ‘‰
    [tÄ±kla](/tr/hakkimda)'
