env: production # to enable google analytics, opengraph, twitter-cards and schema.
description: Personal Blog
author: me
defaultTheme: auto
rssFullContent: true
images:
  - images/avatar.jpg


homeInfoParams:
  Title: Hi there ğŸ‘‹ It's blog about me.
  Content:
    'My wife calls me Buraste ğŸ¦„ I run an online spiritual shop during the day. I swear at night for microservice and give up in the morning ğŸª If you want to know more, check out [about me](/about-me).'

socialIcons:
  - name: twitter
    url: https://twitter.com/helloburaste
  - name: instagram
    url: https://www.instagram.com/burippo/
  - name: stackoverflow
    url: https://stackoverflow.com/users/10890924/mehmet-burak-ibis
  - name: github
    url: https://github.com/burakibis

# Post-specific Params
ShowReadingTime: true
ShowShareButtons: true
ShowBreadCrumbs: true
ShowPostNavLinks: true
comments: true
disableSpecial1stPost: true
showToc: true
TocOpen: true