baseURL = "https://buraste.com/"
title = "buraste"
paginate = 10
theme = "PaperMod"

buildDrafts = false
buildExpired = false
buildFuture = false
enableRobotsTXT = true
googleAnalytics = "UA-221511676-1"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
description = "Personal Blog"
author = "Me"

defaultTheme = "auto"
disableThemeToggle = false
ShowShareButtons = true
ShowReadingTime = true
# disableSpecial1stPost = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
DateFormat = "January 2, 2006"
ShowCodeCopyButtons = true
showtoc = true
# comments = false
images = ["<link or path of image for opengraph, twitter-cards>"]

disableScrollToTop = false
hideSummary = false
hidemeta = false
keywords = ["Blog", "Portfolio", "PaperMod"]
title = "buraste"
tocopen = true

[params.assets]
apple_touch_icon = "/favicon/apple-touch-icon.png"
favicon = "/favicon/favicon.ico"
favicon16x16 = "/favicon/favicon-16x16.png"
favicon32x32 = "/favicon/favicon-32x32.png"
safari_pinned_tab = "/favicon/favicon.ico"

[params.label]
icon = "/img/logo/circle-cropped-removebg-preview.png"
iconHeight = 85
text = "buraste"

#[params.profileMode]
#enabled = false
#imageHeight = 120
#imageTitle = "my image"
#imageUrl = "<img location>"
#imageWidth = 120
#subtitle = "This is subtitle"
#title = "ExampleSite"

#[[params.profileMode.buttons]]
#url = "posts"
#name = "Posts"

[[params.profileMode.buttons]]
url = "tags"
name = "Tags"

[params.homeInfoParams]
Title = "Hi there ğŸ‘‹ It's blog about me."
Content = '''
My wife calls me Buraste ğŸ¦„ I run an online spiritual shop during the day. I write code at night and save the planet. 
Until the next super nova ğŸª you can all sleep soundly. If you want to know more, check out [about me](/about-me).
'''

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/helloburaste"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/burippo/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/10890924/mehmet-burak-ibis"

[[params.socialIcons]]
name = "github"
url = "https://github.com/burakibis"

[params.analytics.google]
SiteVerificationTag = "google-site-verification=aZ0qIoVPzaoZR5ea-XmhDk71jjIQqA-CdGxFLLWR-Yk"

[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
#SiteVerificationTag = "xyzabc"

[params.cover]
hidden = true
hiddenInList = true
hiddenInSingle = false

[params.editPost]
#URL = "https://github.com/burakibis/buraste.com.git/content"
#Text = "Suggest Changes"
#appendFilePath = true

[params.fuseOpts]
#distance = 1_000
#isCaseSensitive = false
#keys = ["title", "permalink", "summary", "content"]
#location = 0
#minMatchCharLength = 0
#shouldSort = true
#threshold = 0.4

[[menu.main]]
identifier = "about"
name = "about me"
url = "/about-me/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "photos"
name = "photos"
url = "https://www.flickr.com/photos/burakibis/"
weight = 30

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

comment = '''
DefaultContentLanguage = "en"
[languages]
    [languages.en]
        title = "burippo.com"
        contentDir = "content/en"
        languageName = "en"
        weight = 1

[languages.tr]
    title = "burippo.com"
    contentDir = "content/tr"
    languageName = "tr"
    weight = 2
    [languages.tr.homeInfoParams]
        Title = "Merhaba ğŸ‘‹ Bu benim hakkÄ±mda bir blog."
        Content = "KarÄ±m bana Buraste diye sesleniyor ğŸ¦„ GÃ¼ndÃ¼zleri online bir spiritÃ¼el dÃ¼kkanÄ± iÅŸletiyorum. Geceleri kod yazÄ±p gezegeni kurtarÄ±yorum ğŸª SÄ±radaki sÃ¼per novaya kadar hepiniz rahat uyuyabilirsiniz. EÄŸer daha fazlasÄ±nÄ± Ã¶ÄŸrenmek istersen [hakkÄ±mda](/about-me) sayfasÄ±nÄ± incele."
    [languages.tr.menu]
        [[languages.tr.menu.main]]
            name = 'hakkÄ±mda'
            url = '/about-me'
            weight = 20
        [[languages.tr.menu.main]]
            name = 'kategoriler'
            url = '/categories'
            weight = 30
        [[languages.tr.menu.main]]
            name = 'fotoÄŸraflar'
            url = 'https://www.flickr.com/photos/burakibis/'
            weight = 40
        [[languages.tr.menu.main]]
            #name = 'seriler'
            #url = '/series'
            #weight = 20
'''